#----------------------------------------------------------------------------------------------------------------------
# XMidiCtrl
#
# Example configuration for the Behringer X-Touch Mini midi controller together with the ToLiss A321
#
# How to use:
#   1. Copy this file into your aircraft directory and rename it to xmidictrl.toml
#   2. Start X-Plane or choose with the Plugin Menu XMidiCtrl -> Reload Aircraft Profile
#----------------------------------------------------------------------------------------------------------------------
title   = "Settings for the ToLiss A321"
version = "0.02"

# Behringer X-Touch Mini
[[device]]
name = "Behringer X-Touch Mini"
port_in = 0
port_out = 1
mapping = [
  #--------------------------------------------------------------------------------------------------------------------
  # Layer A
  #--------------------------------------------------------------------------------------------------------------------

  # Encoders
  { CC = 1, type = "enc", command_up = "sim/instruments/barometer_up", command_down = "sim/instruments/barometer_down" },
  { CC = 2, type = "enc", command_up = "sim/instruments/EFIS_mode_up", command_down = "sim/instruments/EFIS_mode_dn" },
  { CC = 3, type = "enc", command_up = "sim/instruments/map_zoom_out", command_down = "sim/instruments/map_zoom_in" },
  { CC = 4, type = "enc", command_up = "sim/autopilot/airspeed_up", command_down = "sim/autopilot/airspeed_down" },
  { CC = 5, type = "enc", command_up = "sim/autopilot/heading_up", command_down = "sim/autopilot/heading_down" },
  { CC = 6, type = "enc", command_up = "sim/autopilot/altitude_up", command_down = "sim/autopilot/altitude_down" },
  { CC = 7, type = "enc", command_up = "sim/autopilot/vertical_speed_up", command_down = "sim/autopilot/vertical_speed_down" },
  #{ CC = 8, type = "enc", command_up = "", command_down = "" },

  # Encoder Buttons
  #{ CC = 9, type = "pnp", command_push = "", command_pull = "" },
  { CC = 10, type = "cmd", command = "toliss_airbus/dispcommands/CaptCstrPushButton" },
  { CC = 11, type = "cmd", command = "toliss_airbus/dispcommands/TerrOnND1Toggle" },
  { CC = 12, type = "pnp", command_push = "toliss_airbus/spd_pull", command_pull = "toliss_airbus/spd_push" },
  { CC = 13, type = "pnp", command_push = "AirbusFBW/PushHDGSel", command_pull = "AirbusFBW/PullHDGSel" },
  { CC = 14, type = "pnp", command_push = "AirbusFBW/PushAltitude", command_pull = "AirbusFBW/PullAltitude" },
  { CC = 15, type = "pnp", command_push = "toliss_airbus/vs_push", command_pull = "AirbusFBW/PullVSSel" },
  { CC = 16, type = "cmd", command = "sim/transponder/transponder_ident" },

  # Buttons Upper Row
  { CC = 17, type = "cmd", command = "sim/annunciator/clear_master_warning" },
  { CC = 18, type = "cmd", command = "toliss_airbus/fd1_push" },
  { CC = 19, type = "cmd", command = "toliss_airbus/dispcommands/CaptLSButtonPush" },
  { CC = 20, type = "cmd", command = "sim/autopilot/knots_mach_toggle" },
  { CC = 21, type = "cmd", command = "toliss_airbus/hdgtrk_button_push" },
  { CC = 22, type = "drf", dataref = "AirbusFBW/ALT100_1000", value_on = "1", value_off = "0" },
  { CC = 23, type = "cmd", command = "AirbusFBW/EXPEDbutton" },
  #{ CC = 24, type = "cmd", command = "" },

  # Buttons Lower Row
  { CC = 25, type = "cmd", command = "sim/annunciator/clear_master_caution" },
  { CC = 26, type = "cmd", command = "AirbusFBW/TOConfigPress" },
  { CC = 27, type = "drf", dataref = "AirbusFBW/ClockETSwitch", value_on = "1", value_off = "0" },
  { CC = 28, type = "cmd", command = "toliss_airbus/ap1_push" },
  { CC = 29, type = "cmd", command = "AirbusFBW/ATHRbutton" },
  { CC = 30, type = "cmd", command = "toliss_airbus/ap2_push" },
  { CC = 31, type = "cmd", command = "AirbusFBW/APPRbutton" },
  #{ CC = 32, type = "cmd", command = "" },

  #--------------------------------------------------------------------------------------------------------------------
  # Layer B
  #--------------------------------------------------------------------------------------------------------------------

  # Buttons Upper Row
  { CC = 67, type = "cmd", command = "sim/radios/com1_standy_flip" },
  { CC = 68, type = "drf", dataref = "AirbusFBW/SDENG", value_on = "1", value_off = "0" },
  { CC = 69, type = "drf", dataref = "AirbusFBW/SDBLEED", value_on = "1", value_off = "0" },
  { CC = 70, type = "drf", dataref = "AirbusFBW/SDPRESS", value_on = "1", value_off = "0" },
  { CC = 71, type = "drf", dataref = "AirbusFBW/SDELEC", value_on = "1", value_off = "0" },
  { CC = 72, type = "drf", dataref = "AirbusFBW/SDHYD", value_on = "1", value_off = "0" },
  { CC = 73, type = "drf", dataref = "AirbusFBW/SDFUEL", value_on = "1", value_off = "0" },
  { CC = 74, type = "cmd", command = "sim/radios/com2_standy_flip" },

  # Buttons Lower Row
  { CC = 75, type = "cmd", command = "toliss_airbus/aircondcommands/Pack1Toggle" },
  { CC = 76, type = "drf", dataref = "AirbusFBW/SDAPU", value_on = "1", value_off = "0" },
  { CC = 77, type = "drf", dataref = "AirbusFBW/SDCOND", value_on = "1", value_off = "0" },
  { CC = 78, type = "drf", dataref = "AirbusFBW/SDDOOR", value_on = "1", value_off = "0" },
  { CC = 79, type = "drf", dataref = "AirbusFBW/SDWHEEL", value_on = "1", value_off = "0" },
  { CC = 80, type = "drf", dataref = "AirbusFBW/SDFCTL", value_on = "1", value_off = "0" },
  { CC = 81, type = "drf", dataref = "AirbusFBW/SDSTATUS", value_on = "1", value_off = "0" },
  { CC = 82, type = "cmd", command = "toliss_airbus/aircondcommands/Pack2Toggle" }
]