#----------------------------------------------------------------------------------------------------------------------
# XMidiCtrl
#
# Example configuration for the Behringer X-Touch Mini MIDI controller together with the Felis Boeing 747-200
#
# How to use:
#   1. Copy this file into your aircraft directory of the Felis Boeing 747-200 and rename it to XMidiCtrl.toml
#   2. Adjust the port_in and port_out variables
#   3. Start X-Plane or reload the profile from the plugin menu XMidiCtrl -> Reload Aircraft Profile
#----------------------------------------------------------------------------------------------------------------------

title      = "Settings for the Felis 742"
version    = "1.00"
sl_dataref = "xmidictrl/sublayer"

# Behringer X-Touch Mini
[[device]]
name       = "Behringer X-Touch Mini"
port_in    = 0
port_out   = 1
mapping_in = [
  #--------------------------------------------------------------------------------------------------------------------
  # Layer A
  #--------------------------------------------------------------------------------------------------------------------

  # Slider
  { cc = 0,  type = "sld", dataref = "B742/controls/park_brake_lever", value_up = "1", value_down = "0" },

  # Encoders
  { ch = 11, cc = 1, sl = "0", type = "enc", command_up = "sim/instruments/barometer_up", command_down = "sim/instruments/barometer_down" },
  { ch = 11, cc = 1, sl = "1", type = "enc", command_up = "sim/instruments/barometer_stby_up", command_down = "sim/instruments/barometer_stby_down" },
  { ch = 11, cc = 2, type = "enc", command_up = "B742/command/AP_pitch_left_UP", command_down = "B742/command/AP_pitch_left_DOWN" },
  { ch = 11, cc = 3, type = "enc", command_up = "B742/command/AT_speed_up", command_down = "B742/command/AT_speed_down" },
  { ch = 11, cc = 4, type = "enc", command_up = "B742/command/AP_course_1_right", command_down = "B742/command/AP_course_1_left" },
  { ch = 11, cc = 5, type = "enc", command_up = "B742/command/AP_hdg_right", command_down = "B742/command/AP_hdg_left" },
  { ch = 11, cc = 6, type = "enc", command_up = "B742/command/AP_course_2_right", command_down = "B742/command/AP_course_2_left" },
  { ch = 11, cc = 7, type = "enc", command_up = "B742/command/AP_VS_UP", command_down = "B742/command/AP_VS_DOWN" },
  { ch = 11, cc = 8, type = "enc", command_up = "B742/command/AP_ALT_sel_up", command_down = "B742/command/AP_ALT_sel_down" },

  # Encoder Buttons
  { ch = 11, cc = 9,  type = "cmd", command = "xmidictrl/toggle_sublayer" },
  { ch = 11, cc = 10, type = "drf", dataref = "B742/AP_panel/flight_dir_on_sw[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 11, type = "cmd", command = "B742/command/AT_on_off" },
  { ch = 11, cc = 12, type = "drf", dataref = "B742/misc_controls/radio_ins_sw[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 13, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "1" },
  { ch = 11, cc = 14, type = "drf", dataref = "B742/misc_controls/radio_ins_sw[1]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 15, type = "cmd", command = "B742/command/AP_ALT_OFF" },
  { ch = 11, cc = 16, type = "pnp", command_push = "B742/command/AP_ALT_SEL", command_pull = "B742/command/AP_ALT_HOLD" },

  # Buttons Upper Row
  { ch = 11, cc = 17, type = "drf", mode = "momentary", dataref = "B742/AP_mode_panel/AP_RST_button[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 18, type = "cmd", command = "B742/command/AP_A_engage_up" },
  { ch = 11, cc = 19, type = "cmd", command = "B742/command/AP_B_engage_up" },
  { ch = 11, cc = 20, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "0" },
  { ch = 11, cc = 21, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "1" },
  { ch = 11, cc = 22, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "2" },
  { ch = 11, cc = 23, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "3" },
  { ch = 11, cc = 24, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "4" },

  # Buttons Lower Row
  { ch = 11, cc = 25, type = "drf", mode = "momentary", dataref = "B742/AP_mode_panel/AT_RST_button[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 26, type = "cmd", command = "B742/command/AP_A_engage_down" },
  { ch = 11, cc = 27, type = "cmd", command = "B742/command/AP_B_engage_down" },
  { ch = 11, cc = 28, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "-1", value_off = "0" },
  { ch = 11, cc = 29, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "1", value_off = "0" },
  { ch = 11, cc = 30, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "2", value_off = "0" },
  { ch = 11, cc = 31, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "3", value_off = "0" },
  { ch = 11, cc = 32, type = "drf", mode = "momentary", dataref = "B742/misc_controls/instrument_warn_reset_1", value_on = "1", value_off = "0" },
  { ch = 11, cc = 32, type = "drf", mode = "momentary", dataref = "B742/misc_controls/instrument_warn_reset_2", value_on = "1", value_off = "0" },

  #--------------------------------------------------------------------------------------------------------------------
  # Layer B
  #--------------------------------------------------------------------------------------------------------------------

  # Slider
  { ch = 11, cc = 50,  type = "sld", dataref = "B742/controls/park_brake_lever", value_up = "1", value_down = "0" },

  # Encoders
  { ch = 11, cc = 51, type = "enc", command_up = "B742/command/DH_left_UP", command_down = "B742/command/DH_left_DOWN" },
  { ch = 11, cc = 52, type = "enc", command_up = "B742/command/AP_pitch_right_UP", command_down = "B742/command/AP_pitch_right_DOWN" },
  { ch = 11, cc = 53, type = "enc", dataref = "B742/radar/range", modifier_up = 1, modifier_down = -1, value_min = 0, value_max = 4 },
  { ch = 11, cc = 54, sl = "0", type = "enc", command_up = "B742/command/NAV1_freq_small_CW", command_down = "B742/command/NAV1_freq_small_CW" },
  { ch = 11, cc = 54, sl = "1", type = "enc", command_up = "B742/command/NAV1_freq_big_CW", command_down = "B742/command/NAV1_freq_big_CCW" },
  { ch = 11, cc = 55, type = "enc", command_up = "B742/command/AP_nav_select_right", command_down = "B742/command/AP_nav_select_left" },
  { ch = 11, cc = 56, sl = "0", type = "enc", command_up = "B742/command/NAV2_freq_small_CW", command_down = "B742/command/NAV2_freq_small_CCW" },
  { ch = 11, cc = 56, sl = "1", type = "enc", command_up = "B742/command/NAV2_freq_big_CW", command_down = "B742/command/NAV2_freq_big_CCW" },
  { ch = 11, cc = 57, type = "enc", command_up = "B742/command/AP_pitch_up", command_down = "B742/command/AP_pitch_down" },
  { ch = 11, cc = 58, type = "enc", command_up = "B742/command/AP_roll_right", command_down = "B742/command/AP_roll_left" },

  # Encoder Buttons
  { ch = 11, cc = 60, type = "drf", dataref = "B742/AP_panel/flight_dir_on_sw[1]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 61, type = "drf", dataref = "B742/radar/mode_sel", value_on = "4", value_off = "0" },
  { ch = 11, cc = 62, type = "cmd", command = "xmidictrl/toggle_sublayer" },
  { ch = 11, cc = 64, type = "cmd", command = "xmidictrl/toggle_sublayer" },
  { ch = 11, cc = 66, type = "cmd", command = "B742/command/AP_roll_center" },

  # Buttons Upper Row
  { ch = 11, cc = 67, type = "drf", dataref = "B742/clock/ET_switch[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 68, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "0" },
  { ch = 11, cc = 69, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "3" },
  { ch = 11, cc = 70, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "1" },
  { ch = 11, cc = 71, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "2" },
  { ch = 11, cc = 72, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "3" },
  { ch = 11, cc = 73, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "4" },
  { ch = 11, cc = 74, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "5" },

  # Buttons Lower Row
  { ch = 11, cc = 75, type = "drf", mode = "momentary", dataref = "B742/clock/CHR_button[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 76, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "1" },
  { ch = 11, cc = 77, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "2" },
  { ch = 11, cc = 78, type = "drf", dataref = "B742/EPRL/mode_epr_button", value_on = "1", value_off = "0" },
  { ch = 11, cc = 79, type = "drf", dataref = "B742/EPRL/mode_mach_button", value_on = "1", value_off = "0" },
  { ch = 11, cc = 80, type = "drf", dataref = "B742/EPRL/mode_speed_button", value_on = "1", value_off = "0" },
  { ch = 11, cc = 81, type = "drf", dataref = "B742/RMI/needle_1_sel[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 82, type = "drf", dataref = "B742/RMI/needle_2_sel[0]", value_on = "1", value_off = "0" }
]
mapping_out = [
  #--------------------------------------------------------------------------------------------------------------------
  # Layer A
  #--------------------------------------------------------------------------------------------------------------------

  # Buttons Upper Row
  { ch = 11, cc = 17, type = "drf", dataref = ["B742/front_lamps/AP_reset_red_L", "B742/front_lamps/AP_reset_red_R"], value_on = "1", value_off = "0" },
  { ch = 11, cc = 18, type = "drf", dataref = "B742/AP_panel/AP_engage_A", value_on = "1" },
  { ch = 11, cc = 19, type = "drf", dataref = "B742/AP_panel/AP_engage_B", value_on = "1" },
  { ch = 11, cc = 20, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "0" },
  { ch = 11, cc = 21, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "1" },
  { ch = 11, cc = 22, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "2" },
  { ch = 11, cc = 23, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "3" },
  { ch = 11, cc = 24, type = "drf", dataref = "B742/AP_panel/AP_nav_mode_sel", value_on = "4" },

  # Buttons Lower Row
  { ch = 11, cc = 25, type = "drf", dataref = ["B742/front_lamps/AT_reset_red_L", "B742/front_lamps/AT_reset_red_R"], value_on = "1", value_off = "0" },
  { ch = 11, cc = 26, type = "drf", dataref = "B742/AP_panel/AP_engage_A", value_on = "0" },
  { ch = 11, cc = 27, type = "drf", dataref = "B742/AP_panel/AP_engage_B", value_on = "0" },
  { ch = 11, cc = 28, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "-1" },
  { ch = 11, cc = 29, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "1" },
  { ch = 11, cc = 30, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "2" },
  { ch = 11, cc = 31, type = "drf", dataref = "B742/AP_panel/AP_pitch_mode_sel", value_on = "3" },
  { ch = 11, cc = 32, type = "drf", dataref = ["B742/front_lamps/instr_warn_button_lit_L", "B742/front_lamps/instr_warn_button_lit_R"], value_on = "1", value_off = "0" },

  #--------------------------------------------------------------------------------------------------------------------
  # Layer B
  #--------------------------------------------------------------------------------------------------------------------

  # Buttons Upper Row
  { ch = 11, cc = 67, type = "drf", dataref = "B742/clock/ET_switch[0]", value_on = "1", value_off = "0" },
  { ch = 11, cc = 68, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "0" },
  { ch = 11, cc = 69, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "3" },
  { ch = 11, cc = 70, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "1" },
  { ch = 11, cc = 71, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "2" },
  { ch = 11, cc = 72, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "3" },
  { ch = 11, cc = 73, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "4" },
  { ch = 11, cc = 74, type = "drf", dataref = "B742/EPRL/eprl_mode_sel", value_on = "5" },

  # Buttons Lower Row
  { ch = 11, cc = 76, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "1" },
  { ch = 11, cc = 77, type = "drf", dataref = "B742/TCAS/main_mode_sel", value_on = "2" },
  { ch = 11, cc = 78, type = "drf", dataref = "B742/EPRL/mode_epr_button", value_on = "1", value_off = "0" },
  { ch = 11, cc = 79, type = "drf", dataref = "B742/EPRL/mode_mach_button", value_on = "1", value_off = "0" },
  { ch = 11, cc = 80, type = "drf", dataref = "B742/EPRL/mode_speed_button", value_on = "1", value_off = "0" }
]