#----------------------------------------------------------------------------------------------------------------------
# XMidiCtrl
#
# Example configuration for the Behringer X-Touch Mini MIDI controller together with the Hot Start TBM 900
#
# How to use:
#   1. Copy this file into the aircraft directory of the TBM 900 and rename it to XMidiCtrl.toml
#   2. Adjust the port_in and port_out variables
#   3. Start X-Plane or reload the profile from the plugin menu XMidiCtrl -> Reload Aircraft Profile
#----------------------------------------------------------------------------------------------------------------------
title   = "Settings for the Hot Start TBM 900"
version = "0.60"

# Behringer X-Touch Mini
[[device]]
name       = "Behringer X-Touch Mini"
port_in    = 0
port_out   = 1
mapping_in = [
  #--------------------------------------------------------------------------------------------------------------------
  # Layer A
  #--------------------------------------------------------------------------------------------------------------------
  
  # Slider
  { ch = 11, cc = 0, type = "sld", command_up = "tbm900/actuators/ecs/ac_mode_auto", command_middle = "tbm900/actuators/ecs/ac_mode_man", command_down = "tbm900/actuators/ecs/ac_mode_off" },
  
  # Encoders
  { ch = 11, cc = 1, type = "enc", command_up = "sim/GPS/g1000n1_baro_up", command_down = "sim/GPS/g1000n1_baro_down" },
  { ch = 11, cc = 2, type = "enc", command_up = "sim/autopilot/heading_up", command_down = "sim/autopilot/heading_down" },
  { ch = 11, cc = 3, type = "enc", command_up = "sim/GPS/g1000n1_crs_up", command_down = "sim/GPS/g1000n1_crs_down" },
  { ch = 11, cc = 4, type = "enc", command_up = "sim/GPS/g1000n1_range_up", command_down = "sim/GPS/g1000n1_range_down" },
  { ch = 11, cc = 5, type = "enc", command_up = "sim/GPS/g1000n3_range_up", command_down = "sim/GPS/g1000n3_range_down" },
  { ch = 11, cc = 6, type = "enc", command_up = "sim/autopilot/altitude_up", command_down = "sim/autopilot/altitude_down" },
  { ch = 11, cc = 7, type = "enc", command_up = "sim/autopilot/vertical_speed_down", command_down = "sim/autopilot/vertical_speed_up" },
  { ch = 11, cc = 8, type = "enc", command_up = "sim/GPS/g1000n3_crs_up", command_down = "sim/GPS/g1000n3_crs_down" },
    
  # Encoder Buttons
  { ch = 11, cc = 9,  type = "cmd", command = "tbm900/actuators/efis/pfd1_baro_push" },
  { ch = 11, cc = 10, type = "cmd", command = "tbm900/actuators/ap/hdg_sync" },
  { ch = 11, cc = 11, type = "cmd", command = "tbm900/actuators/ap/crs1_dr" },
  { ch = 11, cc = 12, type = "cmd", command = "sim/transponder/transponder_ident" },
  { ch = 11, cc = 13, type = "cmd", command = "sim/GPS/g1000n3_softkey10" },
  { ch = 11, cc = 14, type = "cmd", command = "tbm900/actuators/ap/alt" },
  { ch = 11, cc = 15, type = "cmd", command = "tbm900/actuators/ap/vs" },
  { ch = 11, cc = 16, type = "cmd", command = "tbm900/actuators/ap/crs2_dr" },
    
  # Buttons Upper Row
  { ch = 11, cc = 17, type = "drf", dataref = "sim/cockpit2/radios/actuators/HSI_source_select_pilot", values = ["0", "1", "2"] },
  { ch = 11, cc = 18, type = "cmd", command = "tbm900/actuators/ap/hdg" },
  { ch = 11, cc = 19, type = "cmd", command = "tbm900/actuators/ap/apr" },
  { ch = 11, cc = 20, type = "cmd", command = "tbm900/actuators/ap/nav" },
  { ch = 11, cc = 21, type = "cmd", command = "tbm900/actuators/ap/fd" },
  { ch = 11, cc = 22, type = "cmd", command = "tbm900/actuators/ap/alt" },
  { ch = 11, cc = 23, type = "cmd", command = "tbm900/actuators/ap/vs" },
  { ch = 11, cc = 24, type = "cmd", command = "tbm900/actuators/ap/flc" },
  
  # Buttons Lower Row
  { ch = 11, cc = 25, type = "cmd", command = "sim/annunciator/clear_master_warning" },
  { ch = 11, cc = 26, type = "cmd", command = "sim/annunciator/clear_master_caution" },
  { ch = 11, cc = 27, type = "cmd", command = "tbm900/actuators/ap/bc" },
  { ch = 11, cc = 28, type = "cmd", command = "tbm900/actuators/ap/bank" },
  { ch = 11, cc = 29, type = "cmd", command = "tbm900/actuators/ap/ap" },
  { ch = 11, cc = 30, type = "cmd", command = "tbm900/actuators/ap/yd" },
  { ch = 11, cc = 31, type = "cmd", command = "tbm900/actuators/ap/vnv" },
  { ch = 11, cc = 32, type = "cmd", command = "tbm900/actuators/ap/spd" },
  
  #--------------------------------------------------------------------------------------------------------------------
  # Layer B
  #--------------------------------------------------------------------------------------------------------------------

  # Slider
  { ch = 11, cc = 50, type = "sld", command_up = "tbm900/actuators/ecs/ac_mode_auto", command_middle = "tbm900/actuators/ecs/ac_mode_man", command_down = "tbm900/actuators/ecs/ac_mode_off" },

  # Encoders
  { ch = 11, cc = 51, type = "enc", command_up = "tbm900/actuators/efis/pfd1_nav_vol_up", command_down = "tbm900/actuators/efis/pfd1_nav_vol_down" },
  { ch = 11, cc = 52, type = "enc", command_up = "sim/GPS/g1000n1_fms_outer_up", command_down = "sim/GPS/g1000n1_fms_outer_down" },
  { ch = 11, cc = 53, type = "enc", command_up = "sim/GPS/g1000n1_fms_inner_up", command_down = "sim/GPS/g1000n1_fms_inner_down" },
  { ch = 11, cc = 54, type = "enc", command_up = "sim/GPS/g1000n1_range_up", command_down = "sim/GPS/g1000n1_range_down" },
  { ch = 11, cc = 55, type = "enc", command_up = "sim/GPS/g1000n3_range_up", command_down = "sim/GPS/g1000n3_range_down" },
  { ch = 11, cc = 56, type = "enc", command_up = "sim/GPS/g1000n3_fms_outer_up", command_down = "sim/GPS/g1000n3_fms_outer_down" },
  { ch = 11, cc = 57, type = "enc", command_up = "sim/GPS/g1000n3_fms_inner_up", command_down = "sim/GPS/g1000n3_fms_inner_down" },
  { ch = 11, cc = 58, type = "enc", command_up = "tbm900/actuators/efis/pfd1_com_vol_up", command_down = "tbm900/actuators/efis/pfd1_com_vol_down" },

  # Encoder Buttons
  { ch = 11, cc = 59, type = "cmd", command = "sim/GPS/g1000n1_nvol" },
  { ch = 11, cc = 60, type = "cmd", command = "sim/GPS/g1000n1_cursor" },
  { ch = 11, cc = 61, type = "cmd", command = "sim/GPS/g1000n1_ent" },
  #{ ch = 11, cc = 62, type = "cmd", command = "" },
  #{ ch = 11, cc = 63, type = "cmd", command = "" },
  { ch = 11, cc = 64, type = "cmd", command = "sim/GPS/g1000n3_cursor" },
  { ch = 11, cc = 65, type = "cmd", command = "sim/GPS/g1000n3_ent" },
  { ch = 11, cc = 66, type = "cmd", command = "sim/GPS/g1000n1_cvol" },

  # Buttons Upper Row
  { ch = 11, cc = 67, type = "drf", dataref = "tbm900/switches/ecs/bleed_mode", value_on = "1", value_off = "0" },
  { ch = 11, cc = 68, type = "cmd", command = "tbm900/esi2000/softkey0" },
  { ch = 11, cc = 69, type = "cmd", command = "tbm900/esi2000/softkey1" },
  { ch = 11, cc = 70, type = "cmd", command = "tbm900/esi2000/softkey2" },
  { ch = 11, cc = 71, type = "cmd", command = "tbm900/esi2000/softkey3" },
  { ch = 11, cc = 72, type = "cmd", command = "sim/GPS/g1000n3_direct" },
  { ch = 11, cc = 73, type = "cmd", command = "sim/GPS/g1000n3_menu" },
  { ch = 11, cc = 74, type = "cmd", command = "sim/GPS/g1000n3_clr" },
  
  # Buttons Lower Row
  { ch = 11, cc = 75, type = "cmd", command = "sim/annunciator/clear_master_warning" },
  { ch = 11, cc = 76, type = "cmd", command = "sim/annunciator/clear_master_caution" },
  #{ ch = 11, cc = 77, type = "cmd", command = "" },
  #{ ch = 11, cc = 78, type = "cmd", command = "" },
  #{ ch = 11, cc = 79, type = "cmd", command = "" },
  { ch = 11, cc = 80, type = "cmd", command = "sim/GPS/g1000n3_fpl" },
  { ch = 11, cc = 81, type = "cmd", command = "sim/GPS/g1000n3_proc" },
  { ch = 11, cc = 82, type = "cmd", command = "sim/GPS/g1000n3_ent" }
] 
mapping_out = [
  #--------------------------------------------------------------------------------------------------------------------
  # Layer A
  #--------------------------------------------------------------------------------------------------------------------
  
  # Buttons Upper Row
  { ch = 11, cc = 18, type = "drf", dataref = "tbm900/lights/ap/hdg", value_on = "1", value_off = "0" },
  { ch = 11, cc = 19, type = "drf", dataref = "tbm900/lights/ap/apr", value_on = "1", value_off = "0" },
  { ch = 11, cc = 20, type = "drf", dataref = "tbm900/lights/ap/nav", value_on = "1", value_off = "0" },
  { ch = 11, cc = 22, type = "drf", dataref = "tbm900/lights/ap/alt", value_on = "1", value_off = "0" },
  { ch = 11, cc = 23, type = "drf", dataref = "tbm900/lights/ap/vs", value_on = "1", value_off = "0" },
  { ch = 11, cc = 24, type = "drf", dataref = "tbm900/lights/ap/vnv", value_on = "1", value_iff = "0" },
  
  # Buttons Lower Row
  { ch = 11, cc = 25, type = "drf", dataref = "tbm900/lights/cas/master_warn", value_on = "1", value_off = "0" },
  { ch = 11, cc = 26, type = "drf", dataref = "tbm900/lights/cas/master_caut", value_on = "1", value_off = "0" },
  { ch = 11, cc = 27, type = "drf", dataref = "tbm900/lights/ap/bc", value_on = "1", value_off = "0" },
  { ch = 11, cc = 28, type = "drf", dataref = "tbm900/lights/ap/bank", value_on = "1", value_off = "0" },
  { ch = 11, cc = 29, type = "drf", dataref = "tbm900/lights/ap/ap", value_on = "1", value_off = "0" },
  { ch = 11, cc = 30, type = "drf", dataref = "tbm900/lights/ap/yd", value_on = "1", value_off = "0" },
  { ch = 11, cc = 31, type = "drf", dataref = "tbm900/lights/ap/vnv", value_on = "1", value_off = "0" },
  
  #--------------------------------------------------------------------------------------------------------------------
  # Layer B
  #--------------------------------------------------------------------------------------------------------------------

  # Buttons Upper Row
  { ch = 11, cc = 67, type = "drf", dataref = "tbm900/switches/ecs/bleed_mode", value_on = "1", value_off = "0" },
  
  # Buttons Lower Row
  { ch = 11, cc = 75, type = "drf", dataref = "tbm900/lights/cas/master_warn", value_on = "1", value_off = "0" },
  { ch = 11, cc = 76, type = "drf", dataref = "tbm900/lights/cas/master_caut", value_on = "1", value_off = "0" }
] 